### ISSUE TITLE
ZRC-6 Unoptimised calls of `RequireNotPaused` occur when batch operations are called

### ISSUE THREAD

**Issue by gb3h** [Zilliqa/ZRC#124]
By having the guard clause `RequireNotPaused` in procedures, batch operations result in multiple (wasted) calls to `RequireNotPaused`. When operations occur in large batches, this is a waste of gas fees and network efficiency. 

Procedures affected by this:
- MintToken
- BurnToken
- TransferToken

**Comment by bb111189** [comment]
Thank you. Issued has been resolved
