### ISSUE TITLE
ZRC contracts must have unique names for callback transitions

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/ZRC#88]
For example, the ZRC-1 and ZRC-2 contracts share the same name for a callback, namely `TransferSuccessCallBack`.

This prevents using both of these ZRCs in one user contract because that forces the user to have two `TransferSuccessCallBack` transitions with different type signatures.

**Comment by hicaru** [comment]
one more
* RecipientAcceptTransferFrom
* RecipientAcceptTransfer

**Comment by bb111189** [comment]
Considering there is not much NFT available that requires composability with ZRC-2 tokens within the Zilliqa ecosystem, shall we issue a new ZRC-6 and mark ZRC-1 as deprecated standards?

In this new standard, we give new names to the above name

**Comment by anton-trunov** [comment]
@bb111189 I think that's a solid suggestion. Perhaps we should prefix callbacks with the name of a ZRC, e.g. `ZRC6_ TransferSuccessCallBack` or something like this.

I think @jjcnn had some suggestions too.

**Comment by bb111189** [comment]
Resolved in ZRC-6 https://github.com/Zilliqa/ZRC/pull/98
